Upgrade component ue-tinymce.
universal-editor/tinymce pull request #9
Opened 2017-02-03 16:14 UTC by AlekseySorokin

Upgrade component for tinymce-editor.
Configurated building for project.

2017-02-10 14:23 UTC, muravev approved these changes

2017-02-14 07:16 UTC, niksamokhvalov requested changes

2017-02-14 07:16 UTC, niksamokhvalov commented on README.md
> +Directive to "Universal Editor" editor which extends the possibility of adding a component **ue-tinymce**.
Это же не директивы. Это модуль, содержащий в себе компонент.

2017-02-14 07:16 UTC, niksamokhvalov commented on README.md
>  # Extension for "Universal Editor"
Давай так: TinyMCE component for Universal Editor. Что бы сразу из заголовка было понятно, что это за модуль.

2017-02-14 07:16 UTC, niksamokhvalov commented on bower.json
>    "dependencies": {
А ты не хочешь в зависимостях указать универсальный редактор?

2017-02-14 07:16 UTC, niksamokhvalov commented on package.json
> +  "dependencies": {
Это точно не дев-зависимости?

2017-02-17 13:36 UTC, AlekseySorokin commented on bower.json
>    "dependencies": {
он указан.

2017-02-20 10:00 UTC, niksamokhvalov requested changes

2017-02-20 10:00 UTC, niksamokhvalov commented on README.md
> +    angular.module('myApp', ['universal.editor', 'ue-tinymce']);
Мы можем везде придерживаться одного стиля, писать через дефис `universal-editor`?

2017-02-20 10:00 UTC, niksamokhvalov commented on bower.json
>    "dependencies": {
Он указан в дев-зависимостях. Разве не в основных должен быть?

2017-02-20 10:00 UTC, niksamokhvalov commented on docs/ru/README.md
> +  "component": {
`name` и `component` давай уберём, описывай сразу настройки компонента. Во-первых, компонент может использоваться без связки с полем (ну чисто технически есть такая возможность), во-вторых, механика связывания компонента с полями из API — это часть ядра редактора.

2017-02-20 10:00 UTC, niksamokhvalov commented on docs/ru/README.md
> +## Параметры раздела **settings**
Тут надо сделать таблицу. Сейчас непонятно, какие типы настроек, какие значения по-умолчанию.

2017-02-20 10:01 UTC, niksamokhvalov commented
В коде крайне желательно придерживаться английского языка. Русский только в русской документации.

2017-02-20 10:02 UTC, niksamokhvalov commented
Для ускорения процесса сейчас можешь не писать английскую документацию (в каталоге docs/), можно удалить.

2017-02-21 12:55 UTC, AlekseySorokin commented on bower.json
>    "dependencies": {
нет. Эта зависимость нужна только при разработке. Е

2017-02-21 13:12 UTC, AlekseySorokin commented on README.md
> +    angular.module('myApp', ['universal.editor', 'ue-tinymce']);
Да. точно. Поправил.

2017-02-21 13:13 UTC, AlekseySorokin commented on bower.json
>    "dependencies": {
В сборке она не участвует.

2017-03-01 09:39 UTC, niksamokhvalov requested changes

2017-03-01 09:39 UTC, niksamokhvalov commented on CHANGELOG.md
> +* Разработан модуль `ue-tinymce` для компонентного редактора с компонентом `ue-tinymce` (совместима начиная с версии редактора 1.0.0-alpha4).
Ченджлог на английском нужен.

2017-03-01 12:23 UTC, niksamokhvalov approved these changes

2017-03-01 12:23 UTC, merged